# Site settings
title: Zack Cote
email: zackwcote@gmail.com
description: "a designer in providence, ri"
baseurl: ""
url: "http://zackcote.com"
twitter_username: zackcote_
github_username:  zackcote


# Build settings
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js', '*.command']
permalink: pretty
highlighter: rouge