# Site settings
title: Zack Cote | Designer in Providence, RI
email: zackcote@gmail.com
description: "Zack Cote, a designer in Providence, RI"
url: "zackcote.com"
baseurl: ""

# Build settings
markdown: kramdown
exclude: ['README.md', 'src','node_modules', 'package.json', 'Gruntfile.js', '*.command']
highlighter: false
