# Site settings
title: Zack Cote | Designer in Providence, RI
email: zackcote@gmail.com
description: "Zack Cote, a designer in Providence, RI"
baseurl: ""
url: "http://zackcote.com"

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js', '*.command']
highlighter: true